#!/usr/bin/env python
# coding: utf-8

# TODO: make it pip installable

import os
import sys
import numpy as np
import click
import tqdm
import skimage.io
import traceback

# Root directory of the project
# sys.path.append(ROOT_DIR)  # To find local version of the library
import mrcnn
from mrcnn import utils
import mrcnn.model as modellib
import mrcnn.coco as coco
ROOT_DIR = path = os.path.dirname(mrcnn.__file__)
FAIL_FILES = []
FINISHED_FILES = []
MODEL_DIR = os.path.join('.', "logs")  # TODO: handle these paths better
COCO_MODEL_PATH = os.path.join(ROOT_DIR, "mask_rcnn_coco.h5")

if not os.path.exists(COCO_MODEL_PATH):
    utils.download_trained_weights(COCO_MODEL_PATH)





def crop_image(image, box, headroom=0.0):
    ''' 
        crop image from given box anchors
        boxes are always square and centered around the object
        The box is symmetrically padded before and after to prevent 
        problems with objects close to boundaries
        
        box : [y1, x1, y2, x2]
    '''    
    y1, x1, y2, x2 = box
    x_center = int(( x1 + x2 ) / 2)
    y_center = int(( y1 + y2 ) / 2)
    w, h = image.shape[:2]
    boxw, boxh = abs(x1 - x2), abs(y1 - y2)
    delta_box = abs(boxw - boxh)
    square_h = max(boxw, boxh)
    headroom_pixels = int(square_h * headroom)
    square_h += headroom_pixels

    if square_h % 2 != 0:
        square_h += 1

    padx = (delta_box + headroom_pixels,
              delta_box + headroom_pixels)
    pady = (delta_box + headroom_pixels,
               delta_box + headroom_pixels)

    _image = np.pad(image, (pady, padx, (0, 0)),
                   mode="symmetric")

    crop_x1 = int(x_center - square_h / 2 + padx[0])
    crop_x2 = int(x_center + square_h / 2 + padx[0])
    crop_y1 = int(y_center - square_h / 2 + pady[0])
    crop_y2 = int(y_center + square_h / 2 + pady[0])
    im_crop = _image[crop_y1:crop_y2, crop_x1:crop_x2]
    return im_crop

def filter_roi(rois, _filter):
    ''' filter ROIs according to filter array (boolean list) '''
    assert rois.shape[0] == len(_filter)
    return rois[_filter, :]

def filter_scores(scores, _filter):
    ''' filter scores according to filter list '''
    assert len(scores) == len(_filter)
    return [scores[i] for i in range(len(scores)) if _filter[i]]

def filter_class_ids(class_ids, _filter):
    ''' filter scores according to filter list '''
    assert len(class_ids) == len(_filter)
    return class_ids[_filter]

def filter_masks(masks, _filter):
    ''' filter masks according to filter list '''
    assert masks.shape[-1] == len(_filter)
    return np.concatenate([masks[..., i] for i in range(len(_filter)) if _filter[i]])[..., np.newaxis]

def postprocess_mask(mask):
    ''' boolean array to float image '''
    return mask.squeeze() * 1.0


def infer_file(f_path, model, class_names, target_class, headroom):
    ''' run mask rcnn from image provided path to image'''
    try:
        image_dir = os.path.dirname(f_path)
        image = skimage.io.imread(f_path)

        in_name, in_ext = os.path.splitext(os.path.basename(f_path))

        results = model.detect([image], verbose=0)

        r = results[0]

        c_idx = class_names.index(target_class)
        _filter = [True if _idx == c_idx else False for _idx in r["class_ids"]]

        if True in _filter:
            rr = {
                "rois" : filter_roi(r["rois"], _filter),
                "scores" : filter_scores(r["scores"], _filter),
                "masks" : filter_masks(r["masks"], _filter),
                "class_ids" : filter_class_ids(r["class_ids"], _filter)
            }
            box = list(rr["rois"].squeeze())
            im_crop = crop_image(image, box, headroom)
            mask_crop = crop_image(rr["masks"], box, headroom)

            out_dir = os.path.join(image_dir, os.pardir, "cropped")
            os.makedirs(out_dir, exist_ok=True)
            out_name = ''.join(["cropped_", in_name, in_ext])
            out_name = os.path.join(out_dir, out_name)
            skimage.io.imsave(out_name, im_crop)

            out_dir = os.path.join(image_dir, os.pardir, "mask")
            os.makedirs(out_dir, exist_ok=True)
            out_name = ''.join(["mask_", in_name, in_ext])
            out_name = os.path.join(out_dir, out_name)
            skimage.io.imsave(out_name, postprocess_mask(mask_crop))
            FINISHED_FILES.append(f_path)
        else:
            print("target {} not found in image".format(target_class))
    except Exception as err:
        FAIL_FILES.append(f_path)
        print("error at ", f_path)
        try:
            raise TypeError("Again !?!")
        except:
            pass

        traceback.print_tb(err.__traceback__)


def infer_folder(folder_path, model, class_names, target_class, headroom):
    files = sorted(os.listdir(folder_path))
    print(folder_path)
    for file in tqdm.tqdm(files):
        print(file)
        infer_file(os.path.join(folder_path, file), model, class_names, target_class, headroom)


def print_in_a_frame(words, borderchar = '*'):
    size = max(len(word) for word in words)
    print(borderchar * (size + 4))
    for word in words:
        print('{bc} {:<{}} {bc}'.format(word, size, bc = borderchar))
    print(borderchar * (size + 4))


def print_report():
    print_in_a_frame(["summary - Successful files"])
    msg = "\n".join(FINISHED_FILES)
    print(msg)
    print_in_a_frame(["summary - failed files"])
    msg = "\n".join(FAIL_FILES)
    print(msg)

@click.command()
@click.argument("file_or_folder")
@click.argument("target_class")
@click.option("--headroom", help="ratio of bounding box to expand for cropping", default=0.0)
def main(file_or_folder, target_class, headroom):
    '''
    crop out a target class in an image assuming there is only 1 instance of this class in the image.

    Usage 1 : box_crop cat.jpg cat
        --> outputs centered square crop into ./cropped/cropped_cat.jpg
        --> outputs centered mask crop into ./mask/mask_cat.jpg

    Usage 2 : box_crop frames/ cat
        --> outputs each file in frames a centered square crop into ./cropped/xx.jpg
        --> outputs each file in frames a centered mask crop into ./mask/xx.jpg
    '''
    class InferenceConfig(coco.CocoConfig):
        # Set batch size to 1 since we'll be running inference on
        # one image at a time. Batch size = GPU_COUNT * IMAGES_PER_GPU
        GPU_COUNT = 1
        IMAGES_PER_GPU = 1

    config = InferenceConfig()
    # Create model object in inference mode.
    model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)

    # Load weights trained on MS-COCO
    model.load_weights(COCO_MODEL_PATH, by_name=True)

    class_names = ['BG', 'person', 'bicycle', 'car', 'motorcycle', 'airplane',
                   'bus', 'train', 'truck', 'boat', 'traffic light',
                   'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird',
                   'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear',
                   'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie',
                   'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
                   'kite', 'baseball bat', 'baseball glove', 'skateboard',
                   'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup',
                   'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
                   'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza',
                   'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed',
                   'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote',
                   'keyboard', 'cell phone', 'microwave', 'oven', 'toaster',
                   'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors',
                   'teddy bear', 'hair drier', 'toothbrush']


    if target_class not in class_names:
        print("target class {} not in class names".format(target_class))
        print(class_names)

    if os.path.isdir(file_or_folder):
        infer_folder(file_or_folder, model, class_names, target_class, headroom)
    else:
        print(file_or_folder)
        infer_file(file_or_folder, model, class_names, target_class, headroom)


    print_report()


if __name__ == '__main__':
    main()